### PR TITLE
Fix bug with deleting all rows from table without PK

### LINKED ISSUE #149: Delete from table without primary keys does not work
Looks like `delete from table_without_pk` does not work, find out details and make fix if needed.

### PR DESCRIPTION
**Pull request by mkornaukhov**
In some scans in `RocksDBDatasource` we need only columns that are not stored as effective columns (using RocksDB values), or even we need not any specific column at all as for count query. But we need some column id to construct prefix of RocksDB key to iterate over all existing keys and column specific values. I've named such a column as **effective** one, it means this column **effectively** stored as a RocksDB values. Connector always passes such a column id to `RocksDBDatasource` creation.

### CODE REVIEW

File: server/connector/data_source.cpp [hunk 1]
```diff
@@ -41,14 +41,16 @@ constexpr uint64_t kInitialVectorSize = 1;  // arbitrary value
...
+  std::vector<catalog::Column::Id> column_oids,
+  catalog::Column::Id effective_column_id, ObjectId object_key)
   : velox::connector::DataSource{},
     _memory_pool{memory_pool},
     _snapshot{snapshot},
     _db{db},
     _cf{cf},
     _row_type{std::move(row_type)},
     _column_ids(std::move(column_oids)),
+    _effective_column_id(std::move(effective_column_id)),
```
Comment (Dronplane) [inline server/connector/data_source.cpp:53]: NIT: Do we really need move here?

**Review by MBkkt — APPROVED** [review]

File: server/connector/data_source.cpp (hunk 1 above)
Comment (mkornaukhov) [reply server/connector/data_source.cpp:53]: No, you are right, it has no semantic sense. I just did it by analogy
